/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rotateAdminPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenants"];
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTenant"];
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/sml-connection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        get: operations["getSMLConnection"];
        put: operations["replaceSMLConnection"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/sml-connection/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testSMLConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        get: operations["listRecipients"];
        put?: never;
        post: operations["createRecipientInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/recipients/{recipientId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replaceRecipientPermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        get: operations["listSchedules"];
        put?: never;
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/schedules/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Renders the exact LINE Flex payload with numeric sample values only. This endpoint never queries SML or sends a LINE message. */
        post: operations["previewScheduleFlex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
                scheduleId: components["parameters"]["ScheduleID"];
            };
            cookie?: never;
        };
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/schedules/{scheduleId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/schedules/{scheduleId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenantId}/schedules/{scheduleId}/test-send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicitly queues a fresh SML run and one real LINE Flex delivery per eligible configured recipient. The schedule's next occurrence is unchanged. */
        post: operations["testSendSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/report-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminReportRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/line-quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Provider-wide shared OA quota status. Consumption includes messages sent by other systems and LINE Official Account Manager. */
        get: operations["getLineQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/line-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLineDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/line/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeLineSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutViewer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getViewerMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listViewerTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listViewerReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/executive-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getViewerExecutiveOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/executive-overview/refreshes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createViewerDashboardRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/executive-overview/refreshes/{refreshId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getViewerDashboardRefresh"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/reports/{reportKey}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createViewerReportRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/reports/{reportKey}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getViewerReportRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/reports/{reportKey}/runs/{runId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getViewerReportDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/reports/{reportKey}/runs/{runId}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listViewerReportRows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewer/tenants/{tenantId}/reports/{reportKey}/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelViewerReportRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "ready";
        };
        ProblemEnvelope: {
            error: {
                code: string;
                message: string;
                requestId: string;
                retryable: boolean;
                fieldErrors?: components["schemas"]["FieldError"][];
            };
        };
        FieldError: {
            field: string;
            code: string;
            message: string;
        };
        PageInfo: {
            nextCursor?: string | null;
            hasMore: boolean;
        };
        AdminLoginInput: {
            username: string;
            password: string;
        };
        AdminSession: {
            username: string;
            /** @description Returned on login; subsequent requests may read the same-site CSRF cookie. */
            csrfToken?: string;
            /** Format: date-time */
            expiresAt: string;
            /** @default true */
            mustRotateBootstrapPassword: boolean;
        };
        AdminPasswordInput: {
            currentPassword: string;
            newPassword: string;
        };
        /** @enum {string} */
        TenantStatus: "ACTIVE" | "DISABLED" | "EXPIRED";
        Tenant: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            status: components["schemas"]["TenantStatus"];
            /** Format: date-time */
            accessEndsAt: string;
            version: number;
            /** @enum {string} */
            smlReadiness?: "UNCONFIGURED" | "UNTESTED" | "READY" | "FAILED";
            /** Format: date-time */
            nextScheduleAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TenantInput: {
            slug: string;
            name: string;
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            /** Format: date-time */
            accessEndsAt: string;
        };
        TenantPatch: {
            name?: string;
            /** @enum {string} */
            timezone?: "Asia/Bangkok";
            status?: components["schemas"]["TenantStatus"];
            /** Format: date-time */
            accessEndsAt?: string;
            version: number;
        };
        TenantPage: {
            data: components["schemas"]["Tenant"][];
            page: components["schemas"]["PageInfo"];
        };
        SMLConnectionInput: {
            /**
             * Format: uri
             * @description JavaWS base URL or full endpoint; the standard SMLJavaWebService/DotNetFrameWork path is added to a base URL.
             */
            endpointUrl: string;
            configFileName: string;
            databaseName: string;
            /** @description Optional Basic Auth username; username and password must be supplied together. */
            username?: string;
            /** @description Optional Basic Auth password; username and password must be supplied together. */
            password?: string;
            /** @default 0 */
            version: number;
        };
        SMLConnectionStatus: {
            isConfigured: boolean;
            endpointHost?: string | null;
            databaseName?: string | null;
            configFileName?: string | null;
            /** @enum {string} */
            readinessStatus: "UNTESTED" | "READY" | "FAILED";
            /** Format: date-time */
            lastTestedAt?: string | null;
            lastSafeErrorCode?: string | null;
            version: number;
        };
        SMLConnectionTestResult: {
            /** @enum {string} */
            status: "READY";
            /** Format: date-time */
            testedAt: string;
            latencyMs: number;
        };
        RecipientInput: {
            invitationLabel: string;
        };
        Recipient: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "REVOKED";
            displayName: string;
            reportKeys: components["schemas"]["ReportKey"][];
            /** Format: date-time */
            verifiedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: uri
             * @description Returned only when a pending invitation is created.
             */
            invitationUrl?: string | null;
        };
        RecipientPage: {
            data: components["schemas"]["Recipient"][];
            page: components["schemas"]["PageInfo"];
        };
        PermissionUpdate: {
            reportKeys: components["schemas"]["ReportKey"][];
        };
        /** @enum {string} */
        ReportKey: "sales_goods_services" | "purchase_goods_payables" | "gross_profit_by_product" | "gross_profit_by_ar_customer" | "stock_balance" | "stock_reorder" | "ar_customer_movement" | "ar_debt_receipt" | "cash_bank_receipts" | "cash_bank_payments";
        ReportDefinition: {
            reportKey: components["schemas"]["ReportKey"];
            version: string;
            label: string;
            category: string;
            isSensitive: boolean;
        };
        /** @enum {string} */
        PeriodPreset: "YESTERDAY" | "TODAY_TO_NOW" | "MONTH_TO_DATE" | "AS_OF_RUN";
        /** @enum {string} */
        ScheduleStatus: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
        ScheduleInput: {
            name: string;
            daysOfWeek: number[];
            localTime: string;
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            periodPreset: components["schemas"]["PeriodPreset"];
            reportKeys: components["schemas"]["ReportKey"][];
            recipientIds: string[];
        };
        SchedulePatch: {
            name: string;
            daysOfWeek: number[];
            localTime: string;
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            periodPreset: components["schemas"]["PeriodPreset"];
            reportKeys: components["schemas"]["ReportKey"][];
            recipientIds: string[];
            version: number;
        };
        Schedule: components["schemas"]["ScheduleInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            status: components["schemas"]["ScheduleStatus"];
            version: number;
            readinessBlockers: string[];
            nextOccurrences: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SchedulePage: {
            data: components["schemas"]["Schedule"][];
            page: components["schemas"]["PageInfo"];
        };
        FlexPreviewInput: {
            periodPreset: components["schemas"]["PeriodPreset"];
            reportKeys: components["schemas"]["ReportKey"][];
        };
        FlexPreviewMetric: {
            label: string;
            /** @description Numeric sample value; never customer data. */
            value: string;
        };
        FlexPreviewReport: {
            key: components["schemas"]["ReportKey"];
            label: string;
            metrics: components["schemas"]["FlexPreviewMetric"][];
        };
        FlexPreview: {
            altText: string;
            tenantName: string;
            period: {
                preset: components["schemas"]["PeriodPreset"];
                /** Format: date */
                dateFrom: string;
                /** Format: date */
                dateTo: string;
            };
            periodLabel: string;
            /** Format: date-time */
            generatedAt: string;
            /** Format: uri */
            actionUrl: string;
            reports: components["schemas"]["FlexPreviewReport"][];
            payloadBytes: number;
            /** @description Exact LINE Messaging API Flex message object produced by the backend renderer. */
            message: {
                [key: string]: unknown;
            };
        };
        NotificationExecution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            scheduleId: string;
            /** Format: date-time */
            scheduledFor: string;
            /** @enum {string} */
            status: "COLLECTING" | "FAILED";
            safeErrorCode?: string;
            reportRunIds: string[];
        };
        /** @enum {string} */
        ReportRunStatus: "QUEUED" | "CLAIMED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "EXPIRED";
        CreateReportRunInput: {
            /** @enum {string} */
            periodPreset: "YESTERDAY" | "TODAY_TO_NOW" | "MONTH_TO_DATE" | "AS_OF_RUN" | "CUSTOM";
            /** Format: date */
            dateFrom?: string;
            /** Format: date */
            dateTo?: string;
        };
        ReportRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @description Present on Admin report history responses. */
            tenantName?: string;
            reportKey: components["schemas"]["ReportKey"];
            status: components["schemas"]["ReportRunStatus"];
            periodPreset: string;
            /** Format: date */
            dateFrom?: string | null;
            /** Format: date */
            dateTo?: string | null;
            rowCount: number;
            isTruncated: boolean;
            summary?: {
                [key: string]: unknown;
            };
            reconciliation?: {
                [key: string]: unknown;
            };
            safeErrorCode?: string | null;
            safeErrorMessage?: string | null;
            queuePosition?: number | null;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: date-time */
            expiresAt: string;
        };
        ReportRunPage: {
            data: components["schemas"]["ReportRun"][];
            page: components["schemas"]["PageInfo"];
        };
        ReportRowPage: {
            /** Format: uuid */
            runId: string;
            columns: string[];
            data: {
                [key: string]: unknown;
            }[];
            page: components["schemas"]["PageInfo"];
        };
        ReportPeriod: {
            /** @enum {string} */
            preset: "YESTERDAY" | "TODAY_TO_NOW" | "MONTH_TO_DATE" | "AS_OF_RUN" | "CUSTOM";
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
        };
        /** @enum {string} */
        MetricUnit: "THB" | "COUNT" | "PERCENT" | "QUANTITY" | "RATIO";
        MetricComparison: {
            /** @enum {string} */
            availability: "AVAILABLE" | "UNAVAILABLE";
            previousValue?: string;
            delta?: string;
            percent?: string;
            /** @enum {string} */
            direction?: "UP" | "DOWN" | "SAME";
        };
        DashboardMetric: {
            key: string;
            label: string;
            value: string;
            unit: components["schemas"]["MetricUnit"];
            comparison: components["schemas"]["MetricComparison"];
        };
        VisualizationSeries: {
            key: string;
            label: string;
            values: string[];
            pointLabels?: string[];
        };
        DashboardVisualization: {
            key: string;
            title: string;
            /** @enum {string} */
            intent: "TREND" | "RANKING" | "COMPOSITION" | "EXCEPTION";
            unit: components["schemas"]["MetricUnit"];
            categories: string[];
            series: components["schemas"]["VisualizationSeries"][];
            note?: string;
        };
        DashboardQuality: {
            /** @enum {string} */
            status: "OK" | "WARNING";
            warnings: string[];
        };
        ReportDashboard: {
            reportKey: components["schemas"]["ReportKey"];
            version: string;
            period: components["schemas"]["ReportPeriod"];
            comparisonPeriod: components["schemas"]["ReportPeriod"];
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            /** Format: date-time */
            generatedAt: string;
            kpis: components["schemas"]["DashboardMetric"][];
            visualizations: components["schemas"]["DashboardVisualization"][];
            quality: components["schemas"]["DashboardQuality"];
        };
        DashboardSnapshot: {
            /** Format: uuid */
            runId: string;
            dashboard: components["schemas"]["ReportDashboard"];
        };
        ExecutiveOverview: {
            /** Format: uuid */
            tenantId: string;
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            items: components["schemas"]["DashboardSnapshot"][];
        };
        DashboardRefreshRun: {
            reportKey: components["schemas"]["ReportKey"];
            /** Format: uuid */
            runId: string;
            status: components["schemas"]["ReportRunStatus"];
        };
        DashboardRefresh: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "PARTIAL" | "SUCCEEDED" | "FAILED";
            total: number;
            completed: number;
            failed: number;
            runs: components["schemas"]["DashboardRefreshRun"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        LineSessionInput: {
            idToken: string;
            invitationReference?: string;
            deliveryReference?: string;
        };
        ViewerMe: {
            /** Format: uuid */
            recipientId: string;
            displayName: string;
            csrfToken?: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ViewerTenant: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
            reportKeys: components["schemas"]["ReportKey"][];
        };
        Delivery: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            tenantName: string;
            /** @description Decrypted recipient label for authenticated Admin display only. */
            recipientDisplayName: string;
            /** @enum {string} */
            status: "PENDING" | "SENDING" | "ACCEPTED" | "RETRY_WAIT" | "UNCERTAIN" | "FAILED_PERMANENT";
            attempt: number;
            safeErrorCode?: string | null;
            /** Format: date-time */
            acceptedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        LineQuotaStatus: {
            /** @enum {string} */
            state: "READY" | "UNLIMITED" | "STALE" | "UNSYNCED";
            /** @description Provider target limit; null means unlimited or not yet synced, distinguished by state. */
            providerLimit: number | null;
            /** @description Approximate provider-wide consumption including Nexflow and OA Manager. */
            providerConsumed: number | null;
            /** @description Push messages accepted from Nextstep Dashboard in the current month. */
            locallyAccepted: number;
            operationalReservePercent: number;
            /** Format: date-time */
            syncedAt: string | null;
        };
        DeliveryPage: {
            data: components["schemas"]["Delivery"][];
            page: components["schemas"]["PageInfo"];
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId?: string | null;
            tenantName?: string | null;
            /** @enum {string} */
            actorType: "ADMIN" | "VIEWER" | "WORKER" | "SYSTEM";
            action: string;
            resourceType: string;
            resourceId?: string | null;
            /** @enum {string} */
            result: "SUCCESS" | "DENIED" | "FAILED";
            safeErrorCode?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AuditPage: {
            data: components["schemas"]["AuditEvent"][];
            page: components["schemas"]["PageInfo"];
        };
    };
    responses: {
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        DependencyFailed: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Authentication required or invalid. */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Authenticated identity is not authorized. */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Resource not found. */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Duplicate request, state conflict, or optimistic lock conflict. */
        Problem409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Temporary report rows have expired. */
        Problem410: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Input is syntactically valid but violates a business rule. */
        Problem422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description SML or LINE dependency failed safely. */
        Problem424: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Rate or concurrency limit exceeded. */
        Problem429: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
        /** @description Service is temporarily unavailable. */
        Problem503: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemEnvelope"];
            };
        };
    };
    parameters: {
        TenantID: string;
        RecipientID: string;
        ScheduleID: string;
        RunID: string;
        ReportKey: components["schemas"]["ReportKey"];
        Cursor: string;
        PageSize: number;
        IdempotencyKey: string;
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginInput"];
            };
        };
        responses: {
            /** @description Session created and secure cookie set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current admin session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    rotateAdminPassword: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPasswordInput"];
            };
        };
        responses: {
            /** @description Password rotated and all other sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["TenantStatus"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-paginated tenants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantInput"];
            };
        };
        responses: {
            /** @description Tenant created disabled by default. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant detail and readiness. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantPatch"];
            };
        };
        responses: {
            /** @description Tenant updated with optimistic concurrency. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getSMLConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted connection readiness. Secret values are never returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMLConnectionStatus"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceSMLConnection: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMLConnectionInput"];
            };
        };
        responses: {
            /** @description Connection replaced and marked untested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMLConnectionStatus"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    testSMLConnection: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded connection test result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMLConnectionTestResult"];
                };
            };
            424: components["responses"]["DependencyFailed"];
        };
    };
    listRecipients: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant recipients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientPage"];
                };
            };
        };
    };
    createRecipientInvitation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientInput"];
            };
        };
        responses: {
            /** @description Pending recipient membership created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipient"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    replaceRecipientPermissions: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                recipientId: components["parameters"]["RecipientID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionUpdate"];
            };
        };
        responses: {
            /** @description Entire permission set replaced atomically. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionUpdate"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listSchedules: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant schedules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulePage"];
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleInput"];
            };
        };
        responses: {
            /** @description Draft schedule created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    previewScheduleFlex: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlexPreviewInput"];
            };
        };
        responses: {
            /** @description Backend-rendered single-bubble preview and exact LINE payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlexPreview"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
                scheduleId: components["parameters"]["ScheduleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule and readiness blockers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                scheduleId: components["parameters"]["ScheduleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchedulePatch"];
            };
        };
        responses: {
            /** @description Draft or paused schedule updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    activateSchedule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                scheduleId: components["parameters"]["ScheduleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule activated after all readiness gates pass. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    pauseSchedule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                scheduleId: components["parameters"]["ScheduleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Future occurrences paused; in-flight runs are unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    testSendSchedule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                scheduleId: components["parameters"]["ScheduleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test notification execution accepted for asynchronous report and delivery workers. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationExecution"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listAdminReportRuns: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                tenantId?: string;
                status?: components["schemas"]["ReportRunStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report run history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRunPage"];
                };
            };
        };
    };
    getLineQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe quota metadata without channel credentials. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineQuotaStatus"];
                };
            };
        };
    };
    listLineDeliveries: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                tenantId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted LINE delivery history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryPage"];
                };
            };
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
                tenantId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
        };
    };
    exchangeLineSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineSessionInput"];
            };
        };
        responses: {
            /** @description LINE identity verified and viewer cookie set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    logoutViewer: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viewer session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getViewerMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current verified viewer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listViewerTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active, unexpired tenant memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ViewerTenant"][];
                    };
                };
            };
        };
    };
    listViewerReports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permission-filtered report catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReportDefinition"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getViewerExecutiveOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest compact dashboards for reports authorized to the verified viewer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutiveOverview"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createViewerDashboardRefresh: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A bounded refresh of all authorized reports was queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardRefresh"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    getViewerDashboardRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
                refreshId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current bundle progress derived from its report runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardRefresh"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createViewerReportRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                reportKey: components["parameters"]["ReportKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRunInput"];
            };
        };
        responses: {
            /** @description Fresh SML report run queued. Reuse this run for pagination. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRun"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    getViewerReportRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
                reportKey: components["parameters"]["ReportKey"];
                runId: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized run status and reconciliation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRun"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getViewerReportDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
                reportKey: components["parameters"]["ReportKey"];
                runId: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized KPI and chart-ready aggregates from this report run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDashboard"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listViewerReportRows: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantID"];
                reportKey: components["parameters"]["ReportKey"];
                runId: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-paginated rows from the same report run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRowPage"];
                };
            };
            403: components["responses"]["Forbidden"];
            410: components["responses"]["Gone"];
        };
    };
    cancelViewerReportRun: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                tenantId: components["parameters"]["TenantID"];
                reportKey: components["parameters"]["ReportKey"];
                runId: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued or running report cancellation requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRun"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
}
